### ISSUE TITLE
Port tests tracking issue

### ISSUE THREAD

**Issue by GitGhillie** [GitGhillie/phonon_oxidized#11]
- [ ] PolarVector.test.cpp
- [ ] ProbeTree.test.cpp
- [ ] Quaternion.test.cpp
- [ ] Ray.test.cpp
- [ ] RayTracerCompare.test.cpp
- [ ] Sphere.test.cpp
- [ ] SphericalHarmonics.test.cpp
- [ ] Triangle.test.cpp
- [ ] Vector.test.cpp
